### ISSUE TITLE
distances.py not containing any definition for aml_to_cart.

### ISSUE THREAD

**Issue by elisgrahn** [KIT-MRT/YOLinO#1]
The code in **plot.py** (src/yolino/viz/plot.py) is trying to import **aml_to_cart** from **distances.py** (src/yolino/eval/distances).
```Python
from yolino.eval.distances import aml_to_cart
...
def draw_aml_cell(cell, ...):
    cartesian_cell = torch.ones((len(cell), 4))
    for i, line in enumerate(cell):
        cartesian_cell[i] = aml_to_cart(line)
...
```

However, there isn't any definition for aml_to_cart in distances.py and I can't find it elsewhere.

Could it have been forgotten about?

**Comment by annkitkat** [comment]
Yes, thanks for noting! It should be fixed with 5b3f923d2d0ab780f0227f98da469ee036df9cce
